events {}

http {
    upstream frontend {
        server frontend1:80;
        server frontend2:80;
        server frontend3:80;
    }

    upstream backend {
        server ec2-54-175-59-76.compute-1.amazonaws.com:80;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Node-ID $hostname;
            proxy_pass_header X-Node-ID;
            sub_filter '<head>' '<head><meta name="node-id" content="$hostname">';
            sub_filter_once on;
        }

        location /api/ {
            proxy_pass http://backend/api/;
            proxy_set_header Host ec2-54-175-59-76.compute-1.amazonaws.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                # CORS headers
            add_header 'Access-Control-Expose-Headers' 'X-Node-ID' always;
            # CORS headers
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range,X-Node-ID' always;
            
            # Backend node identification
            proxy_pass_header X-Node-ID;
            proxy_set_header X-Node-ID $upstream_http_x_node_id;
            
            # Handle preflight requests
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                add_header 'Content-Length' 0;
                return 204;
            }
        }
    }
}